Revert "test out using concurrency group"
This reverts commit b5498b2a6346f16dd05a981a6f29b01d925b31ad.

diff --git a/.github/workflows/build-and-lint.yml b/.github/workflows/build-and-lint.yml
--- a/.github/workflows/build-and-lint.yml
+++ b/.github/workflows/build-and-lint.yml
@@ -13,7 +13,14 @@ env:
   LLVM_LINT_VERSION: 15
 
 jobs:
-  Build-LLVM:
+  Build-Standard-LLVM-Linux:
+    uses: ./.github/workflows/llvm-build.yml
+    with:
+      os: ubuntu-22.04
+      c-compiler: clang
+      cpp-compiler: clang++
+
+  Build-LLVM-Others:
     strategy:
       fail-fast: false
       matrix:
@@ -22,7 +29,6 @@ jobs:
           - { os: windows-2022, cpp-compiler: clang-cl, c-compiler: clang-cl, runtime_lib: "MultiThreadedDebug" }
           - { os: windows-2022, cpp-compiler: clang++, c-compiler: clang }
           - { os: windows-2022, cpp-compiler: clang++, c-compiler: clang, sanitizers: "address,undefined" }
-          - { os: ubuntu-22.04, cpp-compiler: clang++, c-compiler: clang }
           - { os: ubuntu-22.04, cpp-compiler: clang++, c-compiler: clang, shared_libs: "ON" }
           - { os: ubuntu-22.04, cpp-compiler: clang++, c-compiler: clang, sanitizers: "thread" }
           - { os: ubuntu-22.04, cpp-compiler: clang++, c-compiler: clang, sanitizers: "address,undefined" }
@@ -38,7 +44,7 @@ jobs:
       shared_libs: ${{matrix.shared_libs}}
 
   Builds:
-    needs: [ Build-LLVM ]
+    needs: [ Build-Standard-LLVM-Linux, Build-LLVM-Others ]
 
     strategy:
       fail-fast: false
@@ -134,3 +140,119 @@ jobs:
         if: always()
         run: |
           Remove-Item -Recurse -Force pylir-build -ErrorAction Ignore
+
+  lint-run:
+    needs: [ Build-Standard-LLVM-Linux ]
+
+    runs-on: ubuntu-22.04
+    steps:
+
+      - name: Install clang-tidy
+        run: |
+          sudo apt-get update
+          sudo apt-get install clang-tidy-$LLVM_LINT_VERSION
+
+      - name: Checkout Pylir
+        uses: actions/checkout@v3
+        with:
+          path: Pylir
+          # Depth 2 because we use git diff HEAD^ later.
+          fetch-depth: 2
+
+      - name: Install Dependencies
+        id: dep-install
+        uses: ./Pylir/.github/actions/dependencies
+        with:
+          c-compiler: clang
+          cpp-compiler: clang++
+
+      # Required by clang-tidy-diff.py.
+      - name: Install Python depends
+        run: |
+          python -m pip install pyyaml
+
+      - name: Fetch LLVM
+        id: llvm-fetch
+        uses: ./Pylir/.github/actions/llvm-fetch
+        with:
+          key: ${{steps.dep-install.outputs.key}}
+
+      - name: Configure Pylir
+        run: |
+          cmake -GNinja -Bpylir-build \
+            -DCMAKE_BUILD_TYPE=Release \
+            -DCMAKE_CXX_COMPILER=clang++ \
+            -DCMAKE_C_COMPILER=clang \
+            -DPython3_ROOT_DIR="$pythonLocation" \
+            -DPython3_FIND_STRATEGY=LOCATION \
+            -DCMAKE_C_COMPILER_LAUNCHER=ccache \
+            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
+            -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" \
+            -DPYLIR_ENABLE_ASSERTIONS=ON \
+            -DLLVM_DIR="${{steps.llvm-fetch.outputs.install-dir}}/lib/cmake/llvm/" \
+            -DMLIR_DIR="${{steps.llvm-fetch.outputs.install-dir}}/lib/cmake/mlir/" \
+            -DLLD_DIR="${{steps.llvm-fetch.outputs.install-dir}}/lib/cmake/lld/" \
+            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
+            -S ${{github.workspace}}/Pylir
+
+      - name: Build Pylir
+        run: |
+          cmake --build pylir-build -- -k0
+
+      # We let clang-tidy output a fixes.yml file. If no warnings have ever been emitted it will be empty, otherwise
+      # we exit with an error code.
+      - name: Run clang-tidy
+        working-directory: ${{github.workspace}}/Pylir
+        run: |
+          git diff -U0 HEAD^ :^3rdParty '***.c' '***.h' '***.hpp' '***.cpp' \
+           | clang-tidy-diff-$LLVM_LINT_VERSION.py -p1 -quiet -use-color -path ${{github.workspace}}/pylir-build \
+             -export-fixes ${{github.workspace}}/fixes.yml -clang-tidy-binary $(which clang-tidy-$LLVM_LINT_VERSION) \
+             -j$(nproc)
+          
+          if [ -s ${{github.workspace}}/fixes.yml ] 
+          then
+            exit 1
+          fi
+
+      - name: Upload clang-tidy fixes.yml
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: fixes.yml
+          path: ${{github.workspace}}/fixes.yml
+
+  format-run:
+    runs-on: ubuntu-22.04
+
+    steps:
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install clang-format-$LLVM_LINT_VERSION
+
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.9
+
+      - name: Checkout Pylir
+        uses: actions/checkout@v3
+        with:
+          # Depth 2 because we need the diff.
+          fetch-depth: 2
+
+      - name: Run clang-format on changes
+        run: |
+          # Below ensures that the exit code of git-clang-format is properly propagated
+          set -o pipefail
+          git diff -U0 HEAD^ :^3rdParty '***.c' '***.h' '***.hpp' '***.cpp' \
+           | clang-format-diff-$LLVM_LINT_VERSION -p1 -binary $(which clang-format-$LLVM_LINT_VERSION) \
+           | tee ${{github.workspace}}/clang-format.patch
+
+      - name: Upload clang-format patch
+        if: ${{ failure() }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: clang-format.patch
+          path: ${{github.workspace}}/clang-format.patch
+
